services:
  - type: web_service
    name: realtime-chat-app
    env: node
    plan: free
    root: backend
    buildCommand: |
      cd ../frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: secret
      - key: JWT_SECRET
        scope: secret
      - key: CLIENT_URL
        value: https://realtime-chat-app.onrender.com
